# Project: MyApp
# Compiler: Default GCC compiler
# Compiler Type: MingW 3
# Makefile created by wxDev-C++ IDE 7.4.2.569 on 09-06-21 20:27

WXLIBNAME = wxmsw29u
CPP       = g++.exe
CC        = gcc.exe
WINDRES   = "windres.exe"
OBJ       = Objects/MingW/MyAppApp.o Objects/MingW/MyAppFrm.o Objects/MingW/MyApp_private.res
LINKOBJ   = "Objects/MingW/MyAppApp.o" "Objects/MingW/MyAppFrm.o" Objects/MingW/MyApp_private.res
LIBS      = -L"C:/Program Files (x86)/Dev-Cpp/lib/wx/gcc_lib" -L"C:/Program Files (x86)/Dev-Cpp/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -mwindows -l$(WXLIBNAME) -l$(WXLIBNAME)_gl -lwxscintilla -lwxtiff -lwxjpeg -lwxpng -lwxzlib -lwxregexu -lwxexpat -lkernel32 -luser32 -lgdi32 -lcomdlg32 -lwinspool -lwinmm -lshell32 -lcomctl32 -lole32 -loleaut32 -luuid -lrpcrt4 -ladvapi32 -lwsock32 -lodbc32 -lopengl32  
INCS      = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include"
CXXINCS   = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/" -I"C:/Program Files (x86)/Dev-Cpp/include/common"
RCINCS    = --include-dir "C:/PROGRA~2/Dev-Cpp/include/common"
BIN       = Output/MingW/MyApp.exe
DEFINES   = -D__WXMSW__ -D__GNUWIN32__ -D_UNICODE
CXXFLAGS  = $(CXXINCS) $(DEFINES)  
CFLAGS    = $(INCS) $(DEFINES)  
GPROF     = gprof.exe
ifeq ($(OS),Windows_NT)
   RM = del /Q
   FixPath = $(subst /,\,$1)
else
   RM = rm -f
   FixPath = $1
endif
LINK      = g++.exe

.PHONY: all all-before all-after clean clean-custom
all: all-before $(BIN) all-after

clean: clean-custom
	$(RM) $(call FixPath,$(LINKOBJ)) "$(call FixPath,$(BIN))"

$(BIN): $(OBJ)
	$(LINK) $(LINKOBJ) -o "$(BIN)" $(LIBS) 

Objects/MingW/MyAppApp.o: $(GLOBALDEPS) MyAppApp.cpp MyAppApp.h MyAppFrm.h
	$(CPP) -c MyAppApp.cpp -o Objects/MingW/MyAppApp.o $(CXXFLAGS)

Objects/MingW/MyAppFrm.o: $(GLOBALDEPS) MyAppFrm.cpp MyAppFrm.h
	$(CPP) -c MyAppFrm.cpp -o Objects/MingW/MyAppFrm.o $(CXXFLAGS)

Objects/MingW/MyApp_private.res: Objects/MingW/MyApp_private.rc MyAppApp.rc 
	$(WINDRES) --input-format=rc -o Objects/MingW/MyApp_private.res $(RCINCS) Objects/MingW/MyApp_private.rc -O coff
